### ISSUE TITLE
Add the DAO minting to the dapp (last 100 mints)

### ISSUE THREAD

**Issue by Dhannte** [ethernautdao/ethernauts#150]
Minting rights
The DAO will have the ability to mint a limited set of 100 NFTs without paying any fees, but without the ability to increase the probability of getting a rarer NFT in any of these mints either. This is so that the DAO can give away some NFTs to community members that were critical to the formation of the DAO, the first set of mentors, etc.

**Comment by mariobyn** [comment]
Let's change this into handling this on the backend... otherwise, the users will pay for the gas of minting 5 nfts and is not ok :D

**Comment by mjlescano** [comment]
Going to close this as is already implemented here: https://github.com/ethernautdao/ethernauts/blob/main/packages/hardhat/contracts/Ethernauts.sol#L262-L270
