### ISSUE TITLE
Emit events where appropriate

### ISSUE THREAD

**Issue by ajsantander** [ethernautdao/ethernauts#48]
So far, main Ethernauts.sol is being developed completely disregarding event emission. It'd be good to review existing functions and see which should emit an event.

Keep in mind that events are already being emitted from the ERC721 contract that is inherited from.

**Comment by avichalp** [comment]
It seems like a good first issue for a newbie. I am new to solidity and want to take a stab at it. 😄

**Comment by StErMi** [comment]
What event do we want to track?

I'll try to make a list

- Sale State Change
- Mint price changed
- Early Mint price changed
- Coupon signer changed
- NFT Gifted

1. are there more events? 
2. from which of these events do we want to track?

**Comment by avichalp** [comment]
Thanks for making the list, @StErMi 

> are there more events?

Do you think we need events for `baseURI` change and `setNextRandomNumber` too?

**Comment by avichalp** [comment]
I created a draft PR [here](https://github.com/ethernautdao/ethernauts/pull/102). To start with, I added four events for: "mint price," "early mint price," "base URI," and "state." This is work in progress. I will add more events as per our discussions.
