### ISSUE TITLE
Research how LOOT composes NFTs

### ISSUE THREAD

**Issue by eternauta1337** [ethernautdao/ethernauts#57]

**Comment by Dhannte** [comment]
Loot NFTs ERC-721 https://etherscan.io/address/0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7

ejemplo:
![image](https://user-images.githubusercontent.com/71194715/136442034-8043ee72-47f3-48d4-8799-b2485d7cdf07.png)

Derivative projects
Loot Dungeon blockchain game incorporating Loot NFTs. By staking your Loot, you can battle a monster with the results determined using Chainlink Verifiable Random Functions that can provide a randomized, on-chain "dice roll". In Loot Dungeon, the Chainlink VRF runs the battles, and unique items are given to the winners with AI-generated pixel art.
Upon entering a Loot dungeon, your Loot NFT is sent to a smart contract. You then have 24 hours to decide to fight the monster or escape. If you die, you will lose your Loot NFT unless you pay a maximum fee of 0.05 ETH.

contract  https://etherscan.io/address/0xdc9d70e37662ce16615224efaa9bb2315b80e36b

This is just a good example of what a community did with Loot NFTs
