### ISSUE TITLE
Error in deploy script

### ISSUE THREAD

**Issue by avichalp** [ethernautdao/ethernauts#80]
Deployment script: `npx hardhat run scripts/deploy.js --network local` throws the following error if the `./deployment` directory is not already present. 

```js
Error: ENOENT: no such file or directory, open './deployments/local.json'
    at Object.openSync (node:fs:506:3)
    at Object.writeFileSync (node:fs:1552:35)
    at main (/Users/avichalpandey/Work/ethernauts/scripts/deploy.js:29:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './deployments/local.json'
}
```

The error is thrown in this line:
```js 
fs.writeFileSync(deploymentPath, JSON.stringify(data, null, 2));
```

A check could be added in the `deploy.js` file to create a directory if it doesn't exist.

**Comment by avichalp** [comment]
Hey @mjlescano,

I was able to make it work locally by changing the following code in `deploy.js`.  But I believe, `fk.mkdir` only works for node v10 and above. If you think it is an acceptable change, I can send a PR. 

```js
   data.token = Ethernauts.address;
-  fs.writeFileSync(deploymentPath, JSON.stringify(data, null, 2));
+
+  fs.mkdir(path.dirname(deploymentPath), { recursive: true }, function (err) {
+    if (err) throw new err();
+    fs.writeFileSync(deploymentPath, JSON.stringify(data, null, 2));
+  });
 }
 ```

**Comment by mjlescano** [comment]
Hey @avichalp , Yes! that would be great and its a good solution. But, could you please the [async/await interface on fsPromises](https://nodejs.org/api/fs.html#fspromisesmkdirpath-options)? 🙏 
Didn't tested it, but it should be something like this:

```javascript
const fs = require('fs/promises')

// ...

  await fs.mkdir(path.dirname(deploymentPath), { recursive: true });
  await fs.writeFile(deploymentPath, JSON.stringify(data, null, 2));

// ...
```

(notice that I also changed `writeFileSync` for `writeFile`)

**Comment by avichalp** [comment]
Thanks, @mjlescano. I tried with the changes you proposed, and it works fine. The `fs` package was already in use at a different place. So I required `fs/promises` as `fsp`.
